config/routes.rb
Guru::Application.routes.draw do

  concern :csv_exportable do
    get :export, on: :collection, :constraints => { format: :csv }
  end

  devise_for :users, skip: [:registrations], path: '', path_names: { sign_in: 'login', sign_out: 'logout' }

  authenticated :user do
    root to: 'dashboard#index'
  end

  namespace :dashboard do
    get :index
    get :visits, constraints: { format: :json }
    get :sources, constraints: { format: :json }
  end

  namespace :members, as: 'member' do
    resource :import, only: [:new, :create], as: 'import'
  end

  resources :members do
    concerns :csv_exportable

    delete :destroy_multiple, on: :collection
    get :active, on: :collection
    get :inactive, on: :collection

    resources :notes, except: [:show, :index], module: 'members'
    resource :account, except: [:show, :destroy]

    resources :payments, except: [:show, :edit, :update] do
      concerns :csv_exportable
    end

    resources :visits, except: :show do
      concerns :csv_exportable
    end
  end

  resources :classes, except: :show, concerns: :csv_exportable
  resources :levels, except: :show, concerns: :csv_exportable
  resources :sources, except: :show, concerns: :csv_exportable

  namespace :settings do
    resource :studio, only: [:edit, :update]
    resource :members, only: [:edit, :update], as: 'member'
    resources :users, except: [:show]
  end

  namespace :reports do
    namespace :members do
      namespace :birthdays do
        get '/(:month)/export', to: :export, as: :export, :constraints => { format: :csv }
        get '/(:month)', to: :index
      end
      namespace :recent do
        get :export
        get '/', to: :index
      end
    end

    namespace :attendance do
      get '/(:month)/(:year)/export', to: :export, as: :export, :constraints => { format: :csv }
      get '/(:month)/(:year)', to: :index
    end

    namespace :accounts do
      get :export, constraints: { format: :csv }
      get '/(:type)', to: :index
    end

    namespace :payments do
      get '/(:month)/(:year)/export', to: :export, as: :export, :constraints => { format: :csv }
      get '/(:month)/(:year)', to: :index
    end
  end

  devise_scope :user do
    root to: 'devise/sessions#new'
  end

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

end

app/views/layouts/shared/_errors.html.haml
- if object.errors.any?
  .error_explanation
    .alert.alert-block.alert-danger
      %button{ 'data-dismiss' => 'alert', class: 'close close-sm', type: 'button'}
        %i.fa.fa-remove
      %ul
        - object.errors.full_messages.each do |msg|
          %li= msg

app/views/layouts/shared/_header.html.haml
/ notify-row start
#top_menu.nav.notify-row
  / notification start
  //= render 'layouts/shared/notifications'
  / notification end
/ notifiy-row end
/ top-nav start
.top-nav.hidden-xs
  %ul.nav.pull-right.top-menu
    %li
      = render 'members/search'
/ top-nav end

app/views/layouts/shared/_messages.html.haml
- flash.each do |key, value|
  %div{ class: "alert alert-block #{flash_class(key)} fade in"}
    %button{ 'data-dismiss' => 'alert', class: 'close close-sm', type: 'button'}
      %i.fa.fa-times
    = value

app/views/layouts/shared/_notifications.html.haml
%ul.nav.top-menu
  / notification dropdown start
  %li#header_notification_bar.dropdown
    %a.dropdown-toggle{"data-toggle" => "dropdown", href: "#"}
      %i.fa.fa-bell
      %span.badge.bg-success 7
    %ul.dropdown-menu.extended.notification
  / notification dropdown end

app/views/layouts/shared/_sidebar.html.haml
%aside
  #sidebar.nav-collapse
    / sidebar menu start
    %ul.sidebar-menu#nav-accordion
      %li
        = link_to '/', class: "#{'active' if controller?('dashboard')}" do
          %i.fa.fa-dashboard
          %span Dashboard
      %li
        = link_to members_path, class: "#{'active' if members_controller?}" do
          %i.fa.fa-user
          %span Members
      %li
        = link_to classes_path, class: "#{'active' if controller?('classes')}" do
          %i.fa.fa-group
          %span Classes
      %li
        = link_to levels_path, class: "#{'active' if controller?('levels')}" do
          %i.fa.fa-list
          %span Levels
      %li
        = link_to sources_path, class: "#{'active' if controller?('sources')}" do
          %i.fa.fa-filter
          %span Sources
      %li.sub-menu
        = link_to '#', class: "#{'active' if reports_controller?}" do
          %i.fa.fa-bar-chart-o
          %span Reports
        %ul.sub
          %li.sub-menu
            = link_to 'Members', '#', {class: "#{'active' if controller?('reports/members/recent') || controller?('reports/members/birthdays')}"}
            %ul.sub
              %li.sub-menu
                %li{class: "#{'active' if controller?('reports/members/recent') && action?('index')}"}
                  = link_to 'Recent', reports_members_recent_path
                %li{class: "#{'active' if controller?('reports/members/birthdays') && action?('index')}"}
                  = link_to 'Birthdays', reports_members_birthdays_path
                  
          %li{class: "#{'active' if controller?('reports/attendance') && action?('index')}"}
            = link_to 'Attendance', reports_attendance_path

          %li{class: "#{'active' if controller?('reports/accounts') && action?('index')}"}
            = link_to 'Accounts', reports_accounts_path

          %li{class: "#{'active' if controller?('reports/payments') && action?('index')}"}
            = link_to 'Payments', reports_payments_path
      %li.sub-menu
        = link_to '#', class: "#{'active' if settings_controller?}" do
          %i.fa.fa-cog
          %span Settings
        %ul.sub
          %li{class: "#{'active' if controller?('settings/studios')}"}
            = link_to 'Studio', edit_settings_studio_path
          %li{class: "#{'active' if controller?('settings/members')}"}
            = link_to 'Members', edit_settings_member_path
          %li{class: "#{'active' if controller?('settings/users')}"}
            = link_to 'Users', settings_users_path
      %li
        = link_to destroy_user_session_path, method: :delete do
          %i.fa.fa-sign-out
          %span Logout
    / sidebar menu end