config/routes.rb
Guru::Application.routes.draw do

  concern :csv_exportable do
    get :export, on: :collection, :constraints => { format: :csv }
  end

  devise_for :users, skip: [:registrations], path: '', path_names: { sign_in: 'login', sign_out: 'logout' }

  authenticated :user do
    root to: 'dashboard#index'
  end

  namespace :dashboard do
    get :index
    get :visits, constraints: { format: :json }
    get :sources, constraints: { format: :json }
  end

  namespace :members, as: 'member' do
    resource :import, only: [:new, :create], as: 'import'
  end

  resources :members do
    concerns :csv_exportable

    delete :destroy_multiple, on: :collection
    get :active, on: :collection
    get :inactive, on: :collection

    resources :notes, except: [:show, :index], module: 'members'
    resource :account, except: [:show, :destroy]

    resources :payments, except: [:show, :edit, :update] do
      concerns :csv_exportable
    end

    resources :visits, except: :show do
      concerns :csv_exportable
    end
  end

  resources :classes, except: :show, concerns: :csv_exportable
  resources :levels, except: :show, concerns: :csv_exportable
  resources :sources, except: :show, concerns: :csv_exportable

  namespace :settings do
    resource :studio, only: [:edit, :update]
    resource :members, only: [:edit, :update], as: 'member'
    resources :users, except: [:show]
  end

  namespace :reports do
    namespace :members do
      namespace :birthdays do
        get '/(:month)/export', to: :export, as: :export, :constraints => { format: :csv }
        get '/(:month)', to: :index
      end
      namespace :recent do
        get :export
        get '/', to: :index
      end
    end

    namespace :attendance do
      get '/(:month)/(:year)/export', to: :export, as: :export, :constraints => { format: :csv }
      get '/(:month)/(:year)', to: :index
    end

    namespace :accounts do
      get :export, constraints: { format: :csv }
      get '/(:type)', to: :index
    end

    namespace :payments do
      get '/(:month)/(:year)/export', to: :export, as: :export, :constraints => { format: :csv }
      get '/(:month)/(:year)', to: :index
    end
  end

  devise_scope :user do
    root to: 'devise/sessions#new'
  end

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

end

app/controllers/classes_controller.rb
class ClassesController < ApplicationController
  include CsvExportable
  before_filter :klass, only: [:edit, :update, :destroy]

  def index
    @klasses = current_studio.klasses.page params[:page]
  end

  def export
    @klasses = current_studio.klasses.all
    export_csv Klass::CsvExport.new(@klasses)
  end

  def new
    @klass = current_studio.klasses.build
  end

  def create
    @klass = current_studio.klasses.build(permitted_params)
    if @klass.save
      redirect_to classes_url, flash: { success: 'Class was successfully created.' }
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @klass.update_attributes(permitted_params)
      redirect_to classes_url, flash: { success: 'Class was successfully updated.' }
    else
      render :edit
    end
  end

  def destroy
    if @klass.destroy
      redirect_to classes_url, flash: { success: 'Class was successfully deleted.' }
    end
  end

  private

  def klass
    @klass = current_studio.klasses.find(params[:id])
  end

  def permitted_params
    params.require(:klass).permit(:day_of_week, :class_time, :name, :recurring)
  end
end

app/views/classes/edit.html.haml
.row
  .col-lg-12
    .panel
      .panel-heading
        Edit Class
      .panel-body
        = form_for @klass, url: class_path(@klass), html: { class: 'form-horizontal' } do |f|
          = render 'layouts/shared/errors', object: @klass
          .form-group
            = f.label :name, 'Name', class: 'col-lg-2 col-sm-2 control-label'
            .col-lg-10
              = f.text_field :name, class: 'form-control'
          .form-group
            = f.label :day_of_week, class: 'col-lg-2 col-sm-2 control-label'
            .col-lg-10
              .input-group
                = f.select :day_of_week, Date::DAYNAMES, selected: Date.current.strftime("%A")
          .form-group
            = f.label :class_time, 'Time', class: 'col-lg-2 col-sm-2 control-label'
            .col-lg-10
              .input-group
                = f.time_select :class_time, {:minute_step => 15, :ampm => true}
          .form-group
            = f.label :recurring, 'Recurring', class: 'col-lg-2 col-sm-2 control-label'
            .col-lg-10
              = f.check_box :recurring, class: 'check_box'
          %br/
          = f.submit 'Update Class', class: 'btn btn-primary'
          = link_to 'Delete Class', class_path(@klass), confirm: 'Are you sure?', method: 'delete', class: 'btn btn-danger'
          = link_to 'Cancel', classes_path, class: 'btn'

app/views/classes/index.html.haml
.row
  .col-lg-12
    .panel
      .panel-heading
        Classes
      .panel-body
        - unless @klasses.empty?
          %table.table.table-hover
            %thead
              %tr
                %th Name
                %th Day of Week
                %th Time
                %th.hidden-xs Recurring
                %th Actions
            %tbody
              - @klasses.each do |klass|
                %tr
                  %td= klass.name
                  %td= klass.day_of_week
                  %td= l klass.class_time, format: :time
                  %td.hidden-xs= icon klass.recurring?, 'check'
                  %td
                    = link_to edit_class_path(klass), class: 'btn btn-sm btn-default' do
                      %i.fa.fa-edit
          .pull-right
            = link_to export_classes_path do
              %i.fa.fa-cloud-download
              Download
          .text-center
            = paginate @klasses
        = link_to 'New Class', new_class_path, class: 'btn btn-primary'

app/views/classes/new.html.haml
.row
  .col-lg-12
    .panel
      .panel-heading
        New Class
      .panel-body
        = form_for @klass, url: classes_path, html: { class: 'form-horizontal' } do |f|
          = render 'layouts/shared/errors', object: @klass
          .form-group
            = f.label :name, 'Name', class: 'col-lg-2 col-sm-2 control-label'
            .col-lg-10
              = f.text_field :name, class: 'form-control'
          .form-group
            = f.label :day_of_week, class: 'col-lg-2 col-sm-2 control-label'
            .col-lg-10
              .input-group
                = f.select :day_of_week, Date::DAYNAMES, selected: Date.current.strftime("%A")
          .form-group
            = f.label :class_time, 'Time', class: 'col-lg-2 col-sm-2 control-label'
            .col-lg-10
              .input-group
                = f.time_select :class_time, {:minute_step => 15, :ampm => true}
          .form-group
            = f.label :recurring, 'Recurring', class: 'col-lg-2 col-sm-2 control-label'
            .col-lg-10
              = f.check_box :recurring, class: 'check_box'
          %br/
          = f.submit 'Create Class', class: 'btn btn-primary'
          = link_to 'Cancel', classes_path, class: 'btn'

app/views/classes/show.html.haml
.row
  .col-lg-12
    .panel
      .panel-heading
        = @klass.name
        = link_to edit_class_path(@klass), class: 'pull-right' do
          %i.fa.fa-edit
      .panel-body
        %dl.dl-horizontal
          %dt Day of Week:
          %dd= @klass.day_of_week
          %dt Time:
          %dd= l @klass.class_time, format: :time
          %dt Recurring:
          %dd= @klass.recurring