config/routes.rb
Guru::Application.routes.draw do

  concern :csv_exportable do
    get :export, on: :collection, :constraints => { format: :csv }
  end

  devise_for :users, skip: [:registrations], path: '', path_names: { sign_in: 'login', sign_out: 'logout' }

  authenticated :user do
    root to: 'dashboard#index'
  end

  namespace :dashboard do
    get :index
    get :visits, constraints: { format: :json }
    get :sources, constraints: { format: :json }
  end

  namespace :members, as: 'member' do
    resource :import, only: [:new, :create], as: 'import'
  end

  resources :members do
    concerns :csv_exportable

    delete :destroy_multiple, on: :collection
    get :active, on: :collection
    get :inactive, on: :collection

    resources :notes, except: [:show, :index], module: 'members'
    resource :account, except: [:show, :destroy]

    resources :payments, except: [:show, :edit, :update] do
      concerns :csv_exportable
    end

    resources :visits, except: :show do
      concerns :csv_exportable
    end
  end

  resources :classes, except: :show, concerns: :csv_exportable
  resources :levels, except: :show, concerns: :csv_exportable
  resources :sources, except: :show, concerns: :csv_exportable

  namespace :settings do
    resource :studio, only: [:edit, :update]
    resource :members, only: [:edit, :update], as: 'member'
    resources :users, except: [:show]
  end

  namespace :reports do
    namespace :members do
      namespace :birthdays do
        get '/(:month)/export', to: :export, as: :export, :constraints => { format: :csv }
        get '/(:month)', to: :index
      end
      namespace :recent do
        get :export
        get '/', to: :index
      end
    end

    namespace :attendance do
      get '/(:month)/(:year)/export', to: :export, as: :export, :constraints => { format: :csv }
      get '/(:month)/(:year)', to: :index
    end

    namespace :accounts do
      get :export, constraints: { format: :csv }
      get '/(:type)', to: :index
    end

    namespace :payments do
      get '/(:month)/(:year)/export', to: :export, as: :export, :constraints => { format: :csv }
      get '/(:month)/(:year)', to: :index
    end
  end

  devise_scope :user do
    root to: 'devise/sessions#new'
  end

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

end

app/models/payment.rb
class Payment < ActiveRecord::Base
  scope :recent, -> { where('payment_date > ?', 90.days.ago).order('payment_date DESC') }

  after_create { |payment| payment.account.payment_made! payment.payment_amount }
  after_destroy { |payment| payment.account.payment_deleted! payment.payment_amount }

  validates_date :due_date, :payment_date
  validates :amount_due, :payment_amount, presence: true

  # credit, check, cash
  classy_enum_attr :payment_method, default: 'check'

  belongs_to :account

  def self.for_month(month = Date.current.month, year = Date.current.year)
    where('extract(month from payment_date) + 0 = ?', month).where('extract(year from payment_date) + 0 = ?', year).order('payment_date DESC')
  end
end

app/models/payment/csv_export.rb
class Payment::CsvExport
  include ActionView::Helpers::NumberHelper

  def initialize(member)
    @member = member
  end

  def filename
    "#{@member.name}_payments.csv"
  end

  def to_csv
    CSV.generate do |csv|
      csv << %w(Payment\ Date Amount\ Paid Due\ Date Amount\ Due Method)
      @member.payments.each do |payment|
        csv << [payment.payment_date.strftime('%m/%d/%Y'), number_to_currency(payment.payment_amount,  unit: ''), payment.due_date.strftime('%m/%d/%Y'), number_to_currency(payment.amount_due,  unit: ''), payment.payment_method]
      end
    end
  end
end

app/controllers/payments_controller.rb
class PaymentsController < InheritedResources::Base
  include AccountRequired
  include CsvExportable

  belongs_to :member
  belongs_to :account, singleton: :true
  actions :all, except: [:show, :edit, :update]
  custom_actions :collection => :export

  before_filter :check_account_exists

  def export
    export_csv Payment::CsvExport.new(@member)
  end

  def create
    create! { member_payments_url(@member) }
  end

  def destroy
    destroy! { member_payments_url(@member) }
  end

  protected

  def collection
    @payments ||= end_of_association_chain.page params[:page]
  end

  private

  def permitted_params
    params.permit(:member_id, payment: [:payment_date, :payment_amount, :due_date, :amount_due, :payment_method])
  end
end

app/controllers/reports/payments_controller.rb
module Reports
  class PaymentsController < ApplicationController
    include ::CsvExportable
    before_filter :report

    def index
      @payments = @report.payments.page params[:page]
    end

    def export
      export_csv @report
    end

    private

    def report
      @report = Report::PaymentReport.new(current_studio, params[:month], params[:year])
    end
  end
end

app/views/payments/_form.html.haml
= form_for [@member, @payment], html: { class: 'form-horizontal' } do |f|
  = render 'layouts/shared/errors', object: @payment
  .form-group
    = f.label :membership_type, 'Membership Type', class: 'col-lg-2 col-sm-2 control-label'
    .col-lg-10
      .input-group
        = f.text_field :membership_type, class: 'form-control', disabled: true, value: @member.membership_type.to_s.capitalize
  .form-group
    = f.label :due_date, 'Due Date', class: 'col-lg-2 col-sm-2 control-label'
    .col-lg-10
      .input-group
        %span.input-group-addon
          %i.fa.fa-calendar
        = f.text_field :due_date, "placeholder data-mask" => "99/99/9999", class: 'form-control', readonly: true, value: l(@member.account_payment_due_date || Date.current)
  .form-group
    = f.label :amount_due, class: 'col-lg-2 col-sm-2 control-label'
    .col-lg-10
      .input-group
        %span.input-group-addon $
        = f.text_field :amount_due, class: 'form-control', readonly: true, value: number_to_currency(@member.account_balance, unit: '', negative_format: "(%u%n)")
  .form-group
    = f.label :payment_date, 'Payment Date', class: 'col-lg-2 col-sm-2 control-label'
    .col-lg-10
      .input-group
        %span.input-group-addon
          %i.fa.fa-calendar
        = f.text_field :payment_date, "placeholder data-mask" => "99/99/9999", "data-date-format" => "mm/dd/yyyy", class: 'form-control datepicker default-date-picker', value: l(Date.current)
  .form-group
    = f.label :payment_amount, 'Payment Amount', class: 'col-lg-2 col-sm-2 control-label'
    .col-lg-10
      .input-group
        %span.input-group-addon $
        = f.text_field :payment_amount, class: 'form-control', value: number_to_currency(@member.default_payment_amount, unit: '')
  .form-group
    = f.label :payment_method, 'Method', class: 'col-lg-2 col-sm-2 control-label'
    .col-lg-10
      = f.select :payment_method, PaymentMethod.all.collect {|t| [t.to_s.capitalize, t.to_s]}
  %br/
  = f.submit nil, class: 'btn btn-primary'
  = link_to 'Cancel', member_payments_path(@member), class: 'btn'

app/views/payments/index.html.haml
.row
  .col-lg-3
    = render 'members/nav'
  .col-lg-9
    .panel
      .panel-heading
        Payments
      .panel-body
        - unless @payments.empty?
          %table.table.table-hover
            %thead
              %tr
                %th Date
                %th Amount
                %th Due Date
                %th Amount Due
                %th Method
                %th Actions
            %tbody
              - @payments.each do |payment|
                %tr
                  %td= l payment.payment_date
                  %td= number_to_currency(payment.payment_amount, negative_format: "(%u%n)")
                  %td= l payment.due_date
                  %td= number_to_currency(payment.amount_due, negative_format: "(%u%n)")
                  %td= payment.payment_method.to_s.capitalize
                  %td
                    = link_to member_payment_path(@member, payment), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-small btn-danger' do
                      %i.fa.fa-trash-o
          .pull-right
            = link_to export_member_payments_path @member do
              %i.fa.fa-cloud-download
              Download
          .text-center
            = paginate @payments
        %br/
        = link_to 'New Payment', new_member_payment_path(@member), class: 'btn btn-primary'

app/views/payments/new.html.haml
.row
  .col-lg-3
    = render 'members/nav'
  .col-lg-9
    .panel
      .panel-heading
        New Payment
      .panel-body
        = render 'form'